### ISSUE TITLE
gpg is missing

### ISSUE THREAD

**Issue by Mosibi** [eilandert/dockerized#2]
gpg is missing which causes issues with the repo validation

```lang=shell
$ podman run --rm -ti eilandert/ubuntu-base:rolling bash

root@f43185bab6ef:/# apt-get update
Get:1 http://deb.paranoid.nl hirsute InRelease [3646 B]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease [23.9 kB]                                                                
Get:3 http://archive.ubuntu.com/ubuntu hirsute InRelease [269 kB]                                              
Err:1 http://deb.paranoid.nl hirsute InRelease                    
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Get:4 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]            
Get:5 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease [90.7 kB]
Ign:2 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease
Get:6 http://security.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Get:7 http://ppa.launchpad.net/ondrej/php/ubuntu groovy/main amd64 Packages [147 kB]
Err:3 http://archive.ubuntu.com/ubuntu hirsute InRelease         
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Err:4 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Err:5 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Err:6 http://security.ubuntu.com/ubuntu hirsute-security InRelease
  gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
Reading package lists... Done
W: GPG error: http://deb.paranoid.nl hirsute InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://deb.paranoid.nl hirsute InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-updates InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-backports InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://security.ubuntu.com/ubuntu hirsute-security InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by eilandert** [comment]
That's strange, I have the following in the Dockerfile and that seems to work for me
COPY    deb.paranoid.nl.gpg /etc/apt/trusted.gpg.d/deb.paranoid.nl.gpg

Also I see no reason why the *ubuntu.com are failing

root@ee7926dc6bc3:/etc/apt/trusted.gpg.d# ls
deb.paranoid.nl.gpg  ubuntu-keyring-2012-cdimage.gpg  ubuntu-keyring-2018-archive.gpg

What do you have there? 

Do you have any suggestions what we can do about it?

**Comment by eilandert** [comment]
I can't reproduce it :-(

root@build:/home/build# podman run --rm -ti eilandert/ubuntu-base:rolling bash

root@444542d06406:/# apt update
Get:1 http://archive.ubuntu.com/ubuntu hirsute InRelease [269 kB]
Get:2 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease [23.9 kB]
Get:3 http://deb.paranoid.nl hirsute InRelease [3646 B]
Get:4 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]
Get:5 http://security.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Get:6 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease [90.7 kB]
Get:7 http://deb.paranoid.nl hirsute/main amd64 Packages [28.6 kB]
Ign:2 http://ppa.launchpad.net/ondrej/php/ubuntu groovy InRelease
Get:8 http://ppa.launchpad.net/ondrej/php/ubuntu groovy/main amd64 Packages [147 kB]
Get:9 http://archive.ubuntu.com/ubuntu hirsute/main amd64 Packages [1791 kB]
Get:10 http://archive.ubuntu.com/ubuntu hirsute/multiverse amd64 Packages [252 kB]
Get:11 http://archive.ubuntu.com/ubuntu hirsute/restricted amd64 Packages [111 kB]
Get:12 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages [16.8 MB]
Get:13 http://security.ubuntu.com/ubuntu hirsute-security/universe amd64 Packages [213 kB]
Get:14 http://security.ubuntu.com/ubuntu hirsute-security/main amd64 Packages [105 kB]
Get:15 http://security.ubuntu.com/ubuntu hirsute-security/multiverse amd64 Packages [1725 B]
Get:16 http://security.ubuntu.com/ubuntu hirsute-security/restricted amd64 Packages [114 kB]
Get:17 http://archive.ubuntu.com/ubuntu hirsute-updates/universe amd64 Packages [243 kB]
Get:18 http://archive.ubuntu.com/ubuntu hirsute-updates/restricted amd64 Packages [114 kB]
Get:19 http://archive.ubuntu.com/ubuntu hirsute-updates/multiverse amd64 Packages [1725 B]
Get:20 http://archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages [186 kB]
Fetched 20.7 MB in 3s (7797 kB/s)
Reading package lists... Done
Building dependency tree... Done

**Comment by eilandert** [comment]
I added the missing gpg for the ondrej ppa on my github

**Comment by Mosibi** [comment]
> I added the missing gpg for the ondrej ppa on my github

Thx.

I can reproduce it on one system (centos 8 stream), but not on another (Fedora Silverblue 34). Even if I create 2 new users, so that I have a complete clean container storage environment, on both systems, I get the same result.

**Comment by Mosibi** [comment]
Further investigation learned me that the issue is in [libseccomp](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1916485). I upgraded the regular Centos8 to Centos8 Stream so that I could upgrade to the latest and greatest, including libseccomp and now the problem is gone.

**Comment by eilandert** [comment]
Thats good to hear, I just installed centos8 in a lxd container.. ;-)
