### ISSUE TITLE
No ngx_http_js_module.so file in libnginx-mod-njs_1.21.4*.deb files

### ISSUE THREAD

**Issue by chaos-dremel** [eilandert/dockerized#4]
It seems that njs module is missing. At least in latest release.

**Comment by eilandert** [comment]
Hi, thanks @chaos-dremel 

It seems the package has been built without the module itself :/   I removed njs from the docker image for now while I am investigating

**Comment by eilandert** [comment]
It has been fixed and I am rebuild/uploading now.
You can apt-get remove libngx-mod-njs as I renamed it to libngx-mod-http-njs

Thanks for your report.

**Comment by chaos-dremel** [comment]
Thanks, now I can use njs module)
